# Generated by Django 3.2 on 2022-07-21 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oyt', '0017_alter_video_is_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='img',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='video',
            name='img_path',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
