# Generated by Django 3.2 on 2022-07-24 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oyt', '0019_auto_20220724_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='tag_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='oyt.tag'),
        ),
    ]
