# Generated by Django 3.2 on 2022-07-24 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oyt', '0020_video_tag_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='user',
        ),
    ]
