# Generated by Django 3.2 on 2022-07-25 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oyt', '0021_remove_tag_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='img',
        ),
        migrations.RemoveField(
            model_name='video',
            name='img_path',
        ),
        migrations.CreateModel(
            name='image',
            fields=[
                ('img_path', models.CharField(max_length=1000, null=True)),
                ('img', models.ImageField(null=True, upload_to='')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('video_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oyt.video')),
            ],
        ),
    ]
