# Generated by Django 3.2 on 2022-07-25 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oyt', '0022_auto_20220725_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='img_path',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
