# Generated by Django 3.2 on 2022-07-26 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oyt', '0024_remove_image_video_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='video',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='oyt.video'),
        ),
    ]
