# Generated by Django 3.2 on 2022-07-26 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oyt', '0025_image_video'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='image',
            new_name='Images',
        ),
    ]
