# Generated by Django 3.2 on 2022-07-26 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oyt', '0026_rename_image_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='img',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
